import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/navbar";
import Footer from "./components/Footer/footer";
import JoinUsPage from "./components/joinus/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="pt-24">
        {children}
        </div>
        <Footer />
        {/* <JoinUsPageOverlay /> */}
      </body>
    </html>
  );
}


function JoinUsPageOverlay() {
  return (
    <div className="z-10">
      <JoinUsPage />
    </div>
  );
}